@echo off
echo Starting Consul locally without Docker...

echo Downloading Consul if not exists...
if not exist consul.exe (
    echo Downloading Consul...
    powershell -Command "Invoke-WebRequest -Uri 'https://releases.hashicorp.com/consul/1.15.2/consul_1.15.2_windows_amd64.zip' -OutFile 'consul.zip'"
    powershell -Command "Expand-Archive -Path 'consul.zip' -DestinationPath '.'"
    del consul.zip
)

echo Starting Consul agent...
start "Consul" consul agent -dev -ui -client=0.0.0.0

echo Consul starting...
echo UI available at: http://localhost:8500